Fix linting issues identified by golangci-lint
tonyskapunk/yctf pull request #18
Opened 2022-10-19 19:37 UTC by komish

The `golangci-lint` tool was added with most linters disabled. This PR:

- bumps the golangci-lint version to 1.49 in the github workflow
- adds a Makefile target that installs golangci-lint for developers to be able to download the exact version they need locally
- adds the output directory of ☝️ to the .gitignore so it's not committed
- enables all linters and fixes discovered issues (except for unused because the flags package is currently not leveraged). 

I opted not to squash these as I figured the code changes should be committed individually.

fixes #14

2022-10-23 21:46 UTC, tonyskapunk requested changes
Thanks for this; let's eliminate the GHA for the linter, and this change will be complete.

2022-10-23 21:46 UTC, tonyskapunk commented on .github/workflows/go_lint.yml
> +          version: v1.49
Released yesterday :smile_cat: 
```suggestion
          version: v1.50
```

2022-10-24 01:16 UTC, komish commented on .github/workflows/go_lint.yml
> +          version: v1.49
@tonyskapunk done.

2022-10-26 02:30 UTC, tonyskapunk approved these changes
Great work here @komish thanks!

2022-10-26 02:30 UTC, merged